title = "Henrik Askøe"
description = """
Henrik Askøe's personal website.
"""
base_url = "https://www.haskoe.dk"
compile_sass = true
highlight_code = true
generate_feed = true
highlight_theme = "charcoal"

[[taxonomies]]
name = "tags"
feed = true